<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xhtml="http://www.w3.org/1999/xhtml"
                exclude-result-prefixes="s xhtml">
    <xsl:output method="html" encoding="UTF-8" indent="yes"/>

    <xsl:template match="/">
        <html>
            <head>
                <title>XML Sitemap</title>
                <style type="text/css">
                    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif; font-size: 16px; color: #333; }
                    table { border-collapse: collapse; width: 100%; }
                    th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }
                    th { background-color: #f2f2f2; font-weight: bold; }
                    a { color: #007bff; text-decoration: none; }
                    a:hover { text-decoration: underline; }
                    .alternates { list-style-type: none; padding-left: 0; }
                    .alternates li { margin-bottom: 5px; }
                    .alternates .lang { font-weight: bold; }
                </style>
            </head>
            <body>
                <h1>XML Sitemap</h1>
                <p>Generated by BharatSaver. This is an XML sitemap, meant for consumption by search engines.</p>
                <table>
                    <thead>
                        <tr>
                            <th>URL</th>
                            <th>Last Modified</th>
                            <th>Change Frequency</th>
                            <th>Priority</th>
                            <th>Hreflang Alternates</th>
                        </tr>
                    </thead>
                    <tbody>
                        <xsl:apply-templates select="s:urlset/s:url"/>
                    </tbody>
                </table>
            </body>
        </html>
    </xsl:template>

    <xsl:template match="s:url">
        <tr>
            <td>
                <a>
                    <xsl:attribute name="href">
                        <xsl:value-of select="s:loc"/>
                    </xsl:attribute>
                    <xsl:value-of select="s:loc"/>
                </a>
            </td>
            <td>
                <xsl:value-of select="s:lastmod"/>
            </td>
            <td>
                <xsl:value-of select="s:changefreq"/>
            </td>
            <td>
                <xsl:value-of select="s:priority"/>
            </td>
            <td>
              <ul class="alternates">
                <xsl:apply-templates select="xhtml:link" />
              </ul>
            </td>
        </tr>
    </xsl:template>

    <xsl:template match="xhtml:link">
      <li>
        <span class="lang"><xsl:value-of select="@hreflang"/>:</span> 
        <a>
            <xsl:attribute name="href">
                <xsl:value-of select="@href"/>
            </xsl:attribute>
            <xsl:value-of select="@href"/>
        </a>
      </li>
    </xsl:template>

</xsl:stylesheet>
