// This file is intentionally left blank.
// The sitemap is now generated by `next-sitemap.config.js` during the `postbuild` step.
// See `next-sitemap.config.js` for the sitemap generation logic.
import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
    return [];
}
